# -*- coding: utf-8 -*-

# Define your item pipelines here
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: https://docs.scrapy.org/en/latest/topics/item-pipeline.html

from scrapy.exceptions import DropItem
from ca_covid_county_spiders.utils.covid import dataHasCovid

# Default pipeline generated by scrapy.
class CaCovidCountySpidersPipeline(object):
    def process_item(self, item, spider):
        return item



# Custom pipeline written by us!
class CovidContentVerificationPipeline(object):
    def process_item(self, item, spider):
        if not dataHasCovid(item):
            raise DropItem('This content is not related to COVID-19.')
        return item